-- WL Credit V25.9 unified upgrade: permanent receipts, customer tags, audit history.
begin;
create extension if not exists pgcrypto;

create or replace function public.wl_current_staff_role() returns text language sql stable security definer set search_path=public as $$ select coalesce((select lower(replace(role,'-','_')) from public.staff_profiles where user_id=auth.uid() and coalesce(is_active,true) limit 1),'') $$;
create or replace function public.wl_is_finance_or_super() returns boolean language sql stable security definer set search_path=public as $$ select public.wl_current_staff_role() in ('finance','super_admin','superadmin') $$;
create or replace function public.wl_is_super_admin() returns boolean language sql stable security definer set search_path=public as $$ select public.wl_current_staff_role() in ('super_admin','superadmin') $$;
grant execute on function public.wl_current_staff_role() to authenticated;
grant execute on function public.wl_is_finance_or_super() to authenticated;
grant execute on function public.wl_is_super_admin() to authenticated;

-- Customer-level tags (not loan-level).
create table if not exists public.customer_tags(id uuid primary key default gen_random_uuid(),name text not null unique,color text not null,description text,sort_order integer not null default 0,is_system boolean not null default false,is_active boolean not null default true,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint customer_tags_color_check check(color ~ '^#[0-9A-Fa-f]{6}$'));
create table if not exists public.customer_tag_assignments(customer_id uuid not null references public.customers(id) on delete cascade,tag_id uuid not null references public.customer_tags(id) on delete restrict,assigned_by uuid,assigned_at timestamptz not null default now(),primary key(customer_id,tag_id));
insert into public.customer_tags(name,color,description,sort_order,is_system) values
('没有还钱','#DC2626','没有还钱 / No repayment',10,true),('慢还钱','#EAB308','慢还钱 / Slow repayment',20,true),('准时还钱','#06B6D4','准时还钱 / Pays on time',30,true),('不能借','#111827','不能借 / Do not lend',40,true)
on conflict(name) do update set color=excluded.color,description=excluded.description,sort_order=excluded.sort_order,is_system=true;
alter table public.customer_tags enable row level security; alter table public.customer_tag_assignments enable row level security;
drop policy if exists "staff read customer tags" on public.customer_tags; create policy "staff read customer tags" on public.customer_tags for select to authenticated using(is_active or public.wl_is_super_admin());
drop policy if exists "super admin manages customer tags" on public.customer_tags; create policy "super admin manages customer tags" on public.customer_tags for all to authenticated using(public.wl_is_super_admin()) with check(public.wl_is_super_admin());
drop policy if exists "staff read visible tag assignments" on public.customer_tag_assignments; create policy "staff read visible tag assignments" on public.customer_tag_assignments for select to authenticated using(public.wl_is_finance_or_super() or exists(select 1 from public.customers c where c.id=customer_id and c.owner_staff_id=auth.uid()));
drop policy if exists "owner manages tag assignments" on public.customer_tag_assignments; create policy "owner manages tag assignments" on public.customer_tag_assignments for all to authenticated using(public.wl_is_super_admin() or exists(select 1 from public.customers c where c.id=customer_id and c.owner_staff_id=auth.uid())) with check(public.wl_is_super_admin() or exists(select 1 from public.customers c where c.id=customer_id and c.owner_staff_id=auth.uid()));
grant select,insert,update,delete on public.customer_tags to authenticated; grant select,insert,delete on public.customer_tag_assignments to authenticated;

-- Permanent private finance receipts.
alter table public.loan_applications add column if not exists finance_proof_path text,add column if not exists finance_proof_name text,add column if not exists finance_proof_uploaded_at timestamptz,add column if not exists finance_proof_uploaded_by uuid;
create table if not exists public.disbursement_receipts(id uuid primary key default gen_random_uuid(),application_id uuid references public.loan_applications(id) on delete restrict,customer_id uuid references public.customers(id) on delete restrict,loan_id uuid references public.loans(id) on delete restrict,owner_staff_id uuid,storage_path text not null unique,original_name text,mime_type text,file_size bigint,uploaded_by uuid not null default auth.uid(),uploaded_at timestamptz not null default now(),created_at timestamptz not null default now());
create index if not exists disbursement_receipts_customer_idx on public.disbursement_receipts(customer_id,uploaded_at desc); create index if not exists disbursement_receipts_loan_idx on public.disbursement_receipts(loan_id,uploaded_at desc);
insert into public.disbursement_receipts(application_id,customer_id,loan_id,owner_staff_id,storage_path,original_name,uploaded_by,uploaded_at)
select a.id,a.customer_id,a.loan_id,coalesce(a.owner_staff_id,a.claimed_by),a.finance_proof_path,a.finance_proof_name,coalesce(a.finance_disbursed_by,a.owner_staff_id,a.claimed_by,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(a.finance_disbursed_at,a.updated_at,a.created_at,now()) from public.loan_applications a where nullif(a.finance_proof_path,'') is not null
on conflict(storage_path) do update set customer_id=coalesce(excluded.customer_id,public.disbursement_receipts.customer_id),loan_id=coalesce(excluded.loan_id,public.disbursement_receipts.loan_id),owner_staff_id=coalesce(excluded.owner_staff_id,public.disbursement_receipts.owner_staff_id);
create or replace function public.wl_receipt_visible(p_application uuid,p_customer uuid,p_owner uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.wl_is_finance_or_super() or p_owner=auth.uid() or exists(select 1 from public.customers c where c.id=p_customer and c.owner_staff_id=auth.uid()) or exists(select 1 from public.loan_applications a where a.id=p_application and coalesce(a.owner_staff_id,a.claimed_by)=auth.uid()) $$;
grant execute on function public.wl_receipt_visible(uuid,uuid,uuid) to authenticated;
alter table public.disbursement_receipts enable row level security;
drop policy if exists "authorized staff read receipts" on public.disbursement_receipts; create policy "authorized staff read receipts" on public.disbursement_receipts for select to authenticated using(public.wl_receipt_visible(application_id,customer_id,owner_staff_id));
drop policy if exists "finance creates receipts" on public.disbursement_receipts; create policy "finance creates receipts" on public.disbursement_receipts for insert to authenticated with check(public.wl_is_finance_or_super() and uploaded_by=auth.uid());
grant select,insert on public.disbursement_receipts to authenticated; revoke update,delete on public.disbursement_receipts from authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('disbursement-proofs','disbursement-proofs',false,10485760,array['image/png','image/jpeg','image/webp','application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "staff upload disbursement proofs" on storage.objects; drop policy if exists "staff read disbursement proofs" on storage.objects;
drop policy if exists "finance uploads permanent proofs" on storage.objects; create policy "finance uploads permanent proofs" on storage.objects for insert to authenticated with check(bucket_id='disbursement-proofs' and public.wl_is_finance_or_super());
drop policy if exists "authorized staff reads proofs" on storage.objects; create policy "authorized staff reads proofs" on storage.objects for select to authenticated using(bucket_id='disbursement-proofs' and exists(select 1 from public.disbursement_receipts r where r.storage_path=name and public.wl_receipt_visible(r.application_id,r.customer_id,r.owner_staff_id)));
-- No UPDATE/DELETE Storage policy: saved receipts cannot be replaced or removed.
create or replace function public.wl_lock_finance_proof() returns trigger language plpgsql security definer set search_path=public as $$ begin if old.finance_proof_path is not null and (new.finance_proof_path is distinct from old.finance_proof_path or new.finance_proof_name is distinct from old.finance_proof_name) then raise exception 'Finance receipt is permanent and cannot be replaced or removed'; end if; if old.finance_proof_path is null and new.finance_proof_path is not null then new.finance_proof_uploaded_at=coalesce(new.finance_proof_uploaded_at,now());new.finance_proof_uploaded_by=coalesce(new.finance_proof_uploaded_by,auth.uid());end if;return new;end $$;
drop trigger if exists wl_lock_finance_proof on public.loan_applications; create trigger wl_lock_finance_proof before update of finance_proof_path,finance_proof_name on public.loan_applications for each row execute function public.wl_lock_finance_proof();
create or replace function public.wl_sync_disbursement_receipt() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.finance_proof_path is not null then insert into public.disbursement_receipts(application_id,customer_id,loan_id,owner_staff_id,storage_path,original_name,uploaded_by,uploaded_at) values(new.id,new.customer_id,new.loan_id,coalesce(new.owner_staff_id,new.claimed_by),new.finance_proof_path,new.finance_proof_name,coalesce(new.finance_proof_uploaded_by,new.finance_disbursed_by,auth.uid()),coalesce(new.finance_proof_uploaded_at,new.finance_disbursed_at,now())) on conflict(storage_path) do update set customer_id=coalesce(excluded.customer_id,public.disbursement_receipts.customer_id),loan_id=coalesce(excluded.loan_id,public.disbursement_receipts.loan_id),owner_staff_id=coalesce(excluded.owner_staff_id,public.disbursement_receipts.owner_staff_id);end if;return new;end $$;
drop trigger if exists wl_sync_disbursement_receipt on public.loan_applications; create trigger wl_sync_disbursement_receipt after insert or update on public.loan_applications for each row execute function public.wl_sync_disbursement_receipt();

-- Complete immutable old -> new history.
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),action text not null,entity_type text,entity_id text,staff_user_id uuid,details text,old_values jsonb,new_values jsonb,changed_fields jsonb,created_at timestamptz not null default now());
alter table public.audit_logs add column if not exists entity_type text,add column if not exists entity_id text,add column if not exists staff_user_id uuid,add column if not exists details text,add column if not exists old_values jsonb,add column if not exists new_values jsonb,add column if not exists changed_fields jsonb;
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type,entity_id,created_at desc); create index if not exists audit_logs_actor_idx on public.audit_logs(staff_user_id,created_at desc);
create or replace function public.wl_jsonb_diff(a jsonb,b jsonb) returns jsonb language sql immutable as $$ select coalesce(jsonb_object_agg(k,jsonb_build_object('old',a->k,'new',b->k)),'{}'::jsonb) from (select key k from jsonb_object_keys(coalesce(a,'{}'::jsonb)) as x(key) union select key from jsonb_object_keys(coalesce(b,'{}'::jsonb)) as y(key))s where a->k is distinct from b->k and k not in('updated_at','last_seen_at') $$;
create or replace function public.wl_audit_row_change() returns trigger language plpgsql security definer set search_path=public as $$ declare o jsonb;n jsonb;d jsonb;eid text;begin o=case when tg_op='INSERT' then null else to_jsonb(old) end;n=case when tg_op='DELETE' then null else to_jsonb(new) end;d=case when tg_op='UPDATE' then public.wl_jsonb_diff(o,n) else coalesce(n,o) end;if tg_op='UPDATE' and d='{}'::jsonb then return new;end if;eid=coalesce(n->>'id',o->>'id',n->>'customer_id',o->>'customer_id');insert into public.audit_logs(action,entity_type,entity_id,staff_user_id,details,old_values,new_values,changed_fields) values(lower(tg_op)||'_'||tg_table_name,tg_table_name,eid,auth.uid(),case when tg_op='UPDATE' then array_to_string(array(select jsonb_object_keys(d)),', ') else tg_op end,o,n,d);return case when tg_op='DELETE' then old else new end;end $$;
do $do$ declare t text;begin foreach t in array array['customers','loans','loan_applications','repayments','payment_submissions','customer_tag_assignments','disbursement_receipts','receiving_banks','company_bank_accounts','staff_bank_allocations','contact_channels'] loop if to_regclass('public.'||t) is not null then execute format('drop trigger if exists wl_audit_change on public.%I',t);execute format('create trigger wl_audit_change after insert or update or delete on public.%I for each row execute function public.wl_audit_row_change()',t);end if;end loop;end $do$;
alter table public.audit_logs enable row level security;
drop policy if exists "super admin reads all audit history" on public.audit_logs; create policy "super admin reads all audit history" on public.audit_logs for select to authenticated using(public.wl_is_super_admin());
drop policy if exists "owner reads related audit history" on public.audit_logs; create policy "owner reads related audit history" on public.audit_logs for select to authenticated using(staff_user_id=auth.uid() or exists(select 1 from public.customers c where c.owner_staff_id=auth.uid() and(c.id::text=entity_id or old_values->>'customer_id'=c.id::text or new_values->>'customer_id'=c.id::text)));
grant select on public.audit_logs to authenticated; revoke update,delete on public.audit_logs from authenticated;
commit;
