const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function setup({customer={},updateError=false,zeroRows=false,rpcData={id:'c1'}}={}){
 const calls={rpc:0,update:[],toasts:[],profiles:[]},button={dataset:{}},form={querySelector:()=>button};
 const values=new Map(Object.entries({name:'Alice',pin:'1234',bank_name:'  Personal Bank  ',bank_account_name:' Alice ',bank_account_number:' 001234 ',bank_id:'company-bank-id',active:'on'}));
 const context={window:null,document:{querySelector:()=>form},FormData:class{get(k){return values.get(k)??null}},crypto:{},Set,console};context.window=context;
 Object.assign(context,{state:{customers:[customer],staff:{}},SWK_LANG:{current:'en'},modal:html=>calls.html=html,toast:m=>calls.toasts.push(m),closeModal:()=>calls.closed=true,loadAll:async()=>{},openCustomerProfile:id=>calls.profiles.push(id),sb:{rpc:async()=>{calls.rpc++;return {data:rpcData}},from:table=>({update:data=>({eq:(k,id)=>({select:()=>({single:async()=>{calls.update.push({table,data,id});return updateError?{error:{message:'database failure'}}:zeroRows?{data:null}:{data:{...data,id}}}})})})})}});
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'customer-personal-bank.js'),'utf8'),context);
 const source=fs.readFileSync(path.join(root,'wl-credit-integrated-v25.8.4.js'),'utf8');vm.runInContext(source.split('/* ===== v25.2-customer-intake-documents.js ===== */')[1].split('/* ===== v25.4-bank-loan-staff-filters.js ===== */')[0],context);
 return {context,calls,form,button,values,submit:()=>form.onsubmit({preventDefault(){}})};
}
test('personal bank aliases and company separation',()=>{const {context}=setup(),read=context.WLCustomerBank.read;const b=read({bank_name:' ',customer_bank_name:'Old Bank',account_name:'A',bank_account:'00123',receiving_bank:{bank_name:'COMPANY',account_number:'999'}});assert.equal(b.bank_name,'Old Bank');assert.equal(b.bank_account_number,'00123');assert.equal(read({receiving_bank:{bank_name:'COMPANY'}}).bank_name,'');assert.equal(read({bank_account_number:'002',account_number:'001'}).bank_account_number,'002')});
test('profile rendering escapes values and displays missing fields',()=>{const {context}=setup();const html=context.WLCustomerBank.card({bank_name:'<script>',bank_account_number:'0012'});assert.match(html,/&lt;script&gt;/);assert.match(html,/0012/);assert.match(html,/Not provided/);assert.doesNotMatch(html,/<script>/)});
test('creation writes personal fields to customers and verifies response',async()=>{const s=setup();s.context.openCustomer();await s.submit();assert.equal(s.calls.rpc,1);const {table,data,id}=s.calls.update[0];assert.equal(table,'customers');assert.equal(id,'c1');assert.equal(data.bank_account_number,'001234');assert.equal(data.assigned_bank_id,'company-bank-id');assert.deepEqual(s.calls.profiles,['c1'])});
test('edit preloads legacy fields and can explicitly clear bank values',async()=>{const s=setup({customer:{id:'c1',customer_bank_name:'Legacy',account_name:'Alice',account_number:'0099'}});s.context.openCustomer('c1');assert.match(s.calls.html,/value="0099"/);s.values.set('bank_account_number','');await s.submit();assert.equal(s.calls.rpc,0);assert.equal(s.calls.update[0].data.bank_account_number,null)});
test('failed second step retries same customer and never reports saved',async()=>{const s=setup({updateError:true});s.context.openCustomer();await s.submit();await s.submit();assert.equal(s.calls.rpc,1);assert.equal(s.calls.update.length,2);assert.equal(s.calls.closed,undefined);assert.match(s.calls.toasts[0],/Customer exists/)});
test('zero updated rows cannot be reported as success',async()=>{const s=setup({zeroRows:true});s.context.openCustomer();await s.submit();assert.equal(s.calls.closed,undefined);assert.match(s.calls.toasts[0],/no row/)});
test('missing create id blocks resubmission and success',async()=>{const s=setup({rpcData:{}});s.context.openCustomer();await s.submit();assert.equal(s.button.disabled,true);assert.equal(s.calls.update.length,0);assert.equal(s.calls.closed,undefined)});
test('double submit creates only once',async()=>{const s=setup();s.context.openCustomer();await Promise.all([s.submit(),s.submit()]);assert.equal(s.calls.rpc,1)});
test('both entry points use repaired UI',()=>{const html=fs.readFileSync(path.join(root,'admin.html'),'utf8');assert.ok(html.indexOf('customer-personal-bank.js')<html.indexOf('extensions.js'));assert.match(fs.readFileSync(path.join(root,'extensions.js'),'utf8'),/WLCustomerBank.card\(c\)/);assert.match(fs.readFileSync(path.join(root,'admin/index.html'),'utf8'),/location.replace/)});
